version: '3'

networks:
  laravel:

services:
  # TODO Env file
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - ./config.env
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php-Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel