version: '3'

networks:
  laravel:

services:
  nginx:
    image: vcarreira/nginx-php7-fpm
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./src/storage/app/public:/var/www/public/storage
      - ./nginx.conf:/etc/nginx/sites-enabled/default.conf
      - ./logs/nginx:/var/log/nginx
    networks:
      - laravel

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - ./config.env
    networks:
      - laravel
